<?php

namespace AymanAlhattami\FilamentContextMenu;

    use Filament\Actions\Action;
use Illuminate\Support\HtmlString;

class ContextMenuDivider extends Action
{
    public static function getDefaultName(): ?string
    {
        return 'divider';
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->view('filament-context-menu::components.divider');
    }
}
